FOP-1360: Add house controller config to U-Boot
fancom/u-boot pull request #2
Opened 2021-07-06 07:47 UTC by 138bit

2021-07-06 14:29 UTC, UberDoefus commented on board/fancom/whc/MAINTAINERS
> +F:	configs/fancom_hc_defconfig
fancom_whc_defconfig

2021-07-06 14:29 UTC, UberDoefus commented on board/fancom/whc/MAINTAINERS
> +F:	include/configs/hc.h
whc.h

2021-07-06 14:29 UTC, UberDoefus commented on board/fancom/whc/MAINTAINERS
> +F:	board/fancom/hc/
board/fancom/whc/

2021-07-06 14:30 UTC, UberDoefus commented on board/fancom/whc/Makefile
> +obj-y	:= hc.o
whc.o

2021-07-06 14:33 UTC, UberDoefus requested changes
Please address the comments

2021-07-07 07:22 UTC, 138bit commented on board/fancom/whc/MAINTAINERS
> +F:	configs/fancom_hc_defconfig
done

2021-07-07 07:22 UTC, 138bit commented on board/fancom/whc/MAINTAINERS
> +F:	include/configs/hc.h
done

2021-07-07 07:22 UTC, 138bit commented on board/fancom/whc/MAINTAINERS
> +F:	board/fancom/hc/
done

2021-07-07 07:22 UTC, 138bit commented on board/fancom/whc/Makefile
> +obj-y	:= hc.o
done

2021-07-07 08:49 UTC, 138bit commented on configs/fancom_whc_defconfig
> +CONFIG_AUTOBOOT_STOP_STR="ef0780D8"
done

2021-07-07 09:17 UTC, UberDoefus approved these changes
All comments addressed

2021-07-07 09:23 UTC, UberDoefus requested changes
Does not boot

2021-07-07 15:03 UTC, UberDoefus approved these changes
Tested and boots

2021-07-07 20:23 UTC, merged